# Generated by Django 5.1.3 on 2024-12-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='Capital_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='Country_no',
            field=models.IntegerField(),
        ),
    ]
