# Generated by Django 5.1.3 on 2024-12-20 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Dept_name', models.CharField(max_length=100)),
                ('Dept_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.IntegerField()),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_job', models.CharField(max_length=100)),
                ('Emp_sal', models.IntegerField()),
                ('Dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
    ]
